services:
  tg-plus-bot:
    build: .
    container_name: tg-plus-bot
    restart: unless-stopped
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_PATH: /app/data/data.db
    volumes:
      - ./data:/app/data
